---
- name: Configure mac workstation
  hosts: localhost
  vars:
    - hostname: LeosMacBookPro
    - projects_directory: Projects
    - dotfiles_repo: git@github.com:lstwn/dotfiles.git
  vars_files:
    - ./vars/packages.yaml
  vars_prompt:
    - name: ssh_key_passphrase
      prompt: ssh key passphrase
    - name: github_access_token
      prompt: github access token
  tasks:
    - import_tasks: ./tasks/hostname_user.yml
    - import_tasks: ./tasks/homebrew.yml
    - import_tasks: ./tasks/app_store.yml
    - import_tasks: ./tasks/dotfiles.yml
    # - import_tasks: ./tasks/ssh.yml
    - import_tasks: ./tasks/npm.yml
    - import_tasks: ./tasks/bluetooth_fix.yml
