---
- name: Configure Mac Workstation
  hosts: localhost
  vars:
    hostname: "LeosMacBookPro"
  vars_files:
    - ./vars/packages.yaml
  vars_prompt:
  tasks:
    - import_tasks: ./tasks/homebrew.yml
    - import_tasks: ./tasks/app_store.yml
    - import_tasks: ./tasks/npm.yml
    - import_tasks: ./tasks/hostname_user.yml
    - import_tasks: ./tasks/system_fixes.yml
