---
- name: update homebrew
  community.general.homebrew:
    update_homebrew: yes
- name: tap homebrew repos
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ tap_repos }}"
- name: install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"
- name: install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ cask_packages }}"
- name: upgrade all installed homebrew packages
  community.general.homebrew:
    upgrade_all: yes
