---
- name: set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
- name: allow fish shell in /etc/shells
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    search_string: /opt/homebrew/bin/fish
    line: /opt/homebrew/bin/fish
- name: set shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    state: present
    shell: /opt/homebrew/bin/fish
    force: no
